Story/p1 76
cook-king-van/cook-king pull request #37
Opened 2022-11-07 01:29 UTC by YunDobi

2022-11-07 01:35 UTC, YunDobi commented
검색후 새로고침 에러하나 잇는데 그건 미팅때 얘기할게요

2022-11-13 06:29 UTC, jayhan1109 requested changes

2022-11-13 06:29 UTC, jayhan1109 commented on client/src/pages/SearchPage.js
> +  // console.log(state)
remove console

2022-11-13 06:29 UTC, jayhan1109 commented on client/src/pages/SearchPage.js
> +  let filteredList = [];
const

2022-11-13 06:29 UTC, jayhan1109 commented on client/src/pages/SearchPage.js
> +  let res = [
const

2022-11-13 06:29 UTC, jayhan1109 commented on client/src/components/navbar/NavBar.js
> +                // console.log(value)
remove

2022-11-13 06:29 UTC, jayhan1109 commented
코드 전체적으로 괜찮은데
여기 왜 아무것도 안뜨지?
<img width="1762" alt="image" src="https://user-images.githubusercontent.com/24958454/201508956-6a6c0437-2a6a-4b8e-8d27-7de580cb51cb.png">

2022-11-13 08:52 UTC, YunDobi commented
고쳤는데 저건 hello 라는 데이터가 없어서 그럼 Silde 1 부터 5 까지 잇음.

2022-11-14 04:18 UTC, closed without merging