story: P1-90
cook-king-van/cook-king pull request #44
Opened 2022-11-19 06:48 UTC by jieunyu0623

2022-11-22 01:14 UTC, jayhan1109 requested changes

2022-11-22 01:14 UTC, jayhan1109 commented on api/recipes/PostRecipe.js
> +      const tmpStep = { ...e, order: index + 1 };
const steps = req.body.step.map((e, index) => {
return { ...e, order: index+1}
})
이렇게 써도 될 거 같은데 한번 확인 고고

2022-11-22 08:21 UTC, younghoonyou commented
<img width="484" alt="스크린샷 2022-11-22 오전 12 20 39" src="https://user-images.githubusercontent.com/69233428/203262090-92ecfd94-c653-4e17-b7fd-9c81bc624eab.png">

UserId 없음요

2022-11-23 20:23 UTC, jieunyu0623 commented
_id 저게 userId 임 @younghoonyou

2022-11-23 23:23 UTC, merged