Story: P1-101
cook-king-van/cook-king pull request #48
Opened 2022-11-25 21:27 UTC by younghoonyou

recipe detail data

recipeName, userName,recipeImage,date

<img width="322" alt="스크린샷 2022-11-25 오후 1 26 27" src="https://user-images.githubusercontent.com/69233428/204056784-622eb87d-b50b-4b05-a5f6-fc779ad8e575.png">
<img width="384" alt="스크린샷 2022-11-25 오후 1 26 44" src="https://user-images.githubusercontent.com/69233428/204056807-f8a8f83d-98ff-4de7-84d0-273ec33bc16e.png">

2022-11-27 04:51 UTC, jayhan1109 requested changes

2022-11-27 04:51 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +    TagRecipes.map((recipe) => {
map은 array를 리턴하고
이렇게 그냥 loop만 돌고 싶을 땐 forEach 함수 사용

2022-11-28 01:07 UTC, younghoonyou commented on api/recipes/SearchRecipe.js
> +    TagRecipes.map((recipe) => {
Js기초 부족이넴ㅠㅠ

2022-12-04 22:04 UTC, jayhan1109 approved these changes
LGTM!

2022-12-05 06:38 UTC, merged