Story/P1-89
cook-king-van/cook-king pull request #54
Opened 2022-12-04 04:58 UTC by jieunyu0623

user profile displays user name, user profile, bio, user recipes and user likes.
<img width="881" alt="Screen Shot 2022-12-03 at 8 57 01 PM" src="https://user-images.githubusercontent.com/55225394/205475259-3ced2729-6942-4c98-98cc-7c2ff789f57f.png">
when there's no recipe to display
<img width="1003" alt="Screen Shot 2022-12-03 at 8 57 12 PM" src="https://user-images.githubusercontent.com/55225394/205475267-55e2fab8-81b1-4f4d-89f5-5472d271c16c.png">

2022-12-04 22:14 UTC, jayhan1109 requested changes

2022-12-04 22:14 UTC, jayhan1109 commented on client/src/components/MyCookingCard.js
> +        <p className='UserProfile-likesDate'>{userId.name ?? '2022.06.23'}</p>
2022.06.23은 나중에 다른 default 값으로 바뀔건가요?

2022-12-04 22:14 UTC, jayhan1109 commented on client/src/pages/UserProfilePage.js
> +                    <MyCookingCard key={i} recipe={recipe} />
key는 index 값으로 쓰면 안됩니당
고유 key로 바꿔주세용

2022-12-04 22:14 UTC, jayhan1109 commented on client/src/pages/UserProfilePage.js
> +                    <MyCookingCard key={i} recipe={like} />
요기도

2022-12-05 23:07 UTC, jieunyu0623 commented on client/src/components/MyCookingCard.js
> +        <p className='UserProfile-likesDate'>{userId.name ?? '2022.06.23'}</p>
이름이 ㅂ반드시 생길겁니다. 지금은 이름을 안가져와서 뒤에 날짜로 넣었어

2022-12-05 23:14 UTC, merged