Story: P1-121 fixed SlideData error
cook-king-van/cook-king pull request #57
Opened 2022-12-07 04:53 UTC by YunDobi

const slideData = [];
allData.map((item, index) => {
    slideData[index] = { caption: item.recipeName, heart: item.likeCount, user: item.userId, url: tempFood };
  });

이런식으로 바꿔줘야만 돌아감!

2022-12-08 22:21 UTC, jayhan1109 approved these changes
LGTM!

2022-12-08 22:23 UTC, jayhan1109 requested changes

2022-12-08 22:23 UTC, jayhan1109 commented on client/src/components/slideshow/MainList.js
> +  allData.map((item, index) => {
const slideData = allData.map((item, index) => {
return { caption: item.recipeName, heart: item.likeCount, user: item.userId, url: tempFood };
})

이렇게 ㄱㄱ

2022-12-10 04:27 UTC, jayhan1109 commented on client/src/components/slideshow/MainList.js
> +  allData.map((item, index) => {
엥 그래?
원래 코드는 slideData[index] = { caption: item.recipeName, heart: item.likeCount, user: item.userId, url: tempFood };
안에 이게 들어가있는데
이거는 확실히 문제가 있거든
slideData가 empty array로 설정이 안되있는데 push 한거니깐
근데 지금 내가 새로 준 코드는 array자체를 새로 하나 만들어주는건데 map으로

저걸로 해서 돌려봤어?

2022-12-10 05:22 UTC, YunDobi commented on client/src/components/slideshow/MainList.js
> +  allData.map((item, index) => {
돌려보니 됫어서 푸쉬 햇어

2022-12-11 05:23 UTC, jayhan1109 approved these changes
LGTM!

2022-12-11 15:14 UTC, merged