Task/p1 103
cook-king-van/cook-king pull request #58
Opened 2022-12-08 23:51 UTC by jieunyu0623

- register error message pop up doesn't go away when x is clicked -> solved it
- refresh token feature implemented

2022-12-09 01:12 UTC, jayhan1109 requested changes

2022-12-09 01:12 UTC, jayhan1109 commented on api/auth/UserValid.js
> +    if (req.headers.authorization.split(' ')[1] === 'null') {
이거 authroziation에 null이 string으로 들어가는 경우가 있어?

2022-12-09 01:12 UTC, jayhan1109 commented on client/src/utils/SetAuthToken.js
> +const setAuthToken = (token, isLocal) => {
const storage = isLocal ? localStorage : sessionStorage
이렇게 해주고
밑에는 그냥 storage.setItem, storage.removeItem 해주면 깔끔 할 듯

2022-12-10 01:05 UTC, jieunyu0623 commented on api/auth/UserValid.js
> +    if (req.headers.authorization.split(' ')[1] === 'null') {
응 api 파일 가면     config.headers['Authorization'] = `Bearer ${
      localStorage.getItem('token') || sessionStorage.getItem('token')
    }`; 해서 토큰 설정 해서 만약 없으면 null string으로 나와서 그래. 바꿀까??

2022-12-11 05:40 UTC, jayhan1109 approved these changes
LGTM

2022-12-11 05:43 UTC, merged