Story: P1-118 Pagination
cook-king-van/cook-king pull request #66
Opened 2022-12-18 07:54 UTC by younghoonyou

Search Pagination

path : /api/recipes/search?name=${searchName}&page=${Number}

Number is always positive

<img width="1268" alt="스크린샷 2022-12-17 오후 11 39 30" src="https://user-images.githubusercontent.com/69233428/208287399-d7eaac31-c572-4e5c-9aed-992246b4cd1f.png">

Q: In C/C++ static variable is stored in Data part in memory, but I don't know the expression of async static variable in Js deeply

- let currentpage = 0;
- let remainNumber = 0;

To link easily between Recipe and Tag collection
ex) Recipe Num = 5 , Tag Num = 4 , pagecntNum = 3
-> when page = 2 Recipe Num left 2 so we need one more recipe from Tag (3*2 - 5) = 1
-> And from page = 3 I have to get recipe only from Tag so it will start from [ remain + page - (CheckedPage + 1)]
-> so I have to check termination page between two collection and Tag's addition num [CheckedPage, remain]

2022-12-18 19:55 UTC, jayhan1109 requested changes

2022-12-18 19:55 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +      // const skipNumber;
지우기

2022-12-18 19:55 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +      let skipNumber;
이것도 위에 3번째 remainNumber, currentPage 정의한 곳에 넣는게 나을듯

2022-12-19 07:34 UTC, jayhan1109 requested changes

2022-12-19 07:34 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +let currentpage = 0;
>Q: In C/C++ static variable is stored in Data part of memory, but I don't know the expression of async static variable in Js deeply
let currentpage = 0;
let remainNumber = 0;

이거 그냥 6번째줄 try 위에다가 만들면 될 거 같아

3,4번째 줄에 쓰면 global variable이 되면서 c++에 static이랑 비슷해지긴 하는데
지금은 6번째줄 try위에다가 만들어도 크게 문제가 없어보여.

skipNumber도 같이 선언 ㄱㄱ

2022-12-19 07:36 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +let currentpage = 0;
아 잠깐만 이거 function 불러올 때 마다 그 이전 값이 저장이 되어야 되는거구나
그러면 이거 이렇게 쓰면 안될 거 같아

2022-12-19 07:37 UTC, jayhan1109 commented on api/recipes/SearchRecipe.js
> +let currentpage = 0;
내 생각엔 c++의 static 처럼 쓰는건 힘들거 같고
server에서 front쪽으로 remainNumber랑 currentPage를 넘겨주고
다시 front쪽에서 remainNumber랑 currentPage를 server쪽으로 받아와야 할 거 같아

2022-12-19 07:47 UTC, jayhan1109 commented
지은이랑 윤철이랑 이야기 했는데
today's best, brunch, snack, dinner 이 옵션들에 대한 값에 대한 처리
category에 대한 처리
search bar에 대한 처리
이 3개의 경우를 각각 처리해줘야 할 거 같아

front에서 query.name, query.subject, query.page 이렇게 3개를 받아서
subject에 따라서 처리 해주는거지

if(subject === 'option')
today's best, brunch, snack, dinner 처리

if(subject==='category')
category에 관련된 처리

if(subject ==='searchBar')
searchBar로 들어온 keyword에 대한 처리

2022-12-19 07:47 UTC, jayhan1109 commented
만약에 좀 이해가 안되면 나랑 평일에 디코 고고

2022-12-20 03:15 UTC, younghoonyou commented
이 모든게 한 파일이 아닌 분산해서 api각각 만들어도되는거지? 어차피 버튼이 있으니깐 하지만 return되는 타입은 모두같게

2022-12-20 05:20 UTC, jayhan1109 commented
ㅇㅇ 하나에서 해도 되고 나눠서 해도 되고

2022-12-28 19:52 UTC, jayhan1109 approved these changes
Good!

2022-12-28 21:30 UTC, merged