Story/p1 115
cook-king-van/cook-king pull request #72
Opened 2022-12-21 01:49 UTC by YunDobi

see more buttons in LandingPage

https://user-images.githubusercontent.com/88572626/208801260-b38340fb-4dd3-4f26-8dee-f2624423d510.mov

Categories button

https://user-images.githubusercontent.com/88572626/208801323-6655a0b0-5c52-4d5f-b94b-82217bf238d7.mov

Searching  with URL

https://user-images.githubusercontent.com/88572626/208801425-1b04938f-0a55-498d-acb3-2020c1e7ff81.mov

2022-12-21 22:48 UTC, jayhan1109 commented
see more buttons in LandingPage 작동은 잘 하는데 + 버튼이 위치가 좀 이상해
고치고 있는거야??

2022-12-21 22:48 UTC, jayhan1109 commented
로딩 스크린 지은이가 추가한 걸로 바꿔줘

2022-12-21 22:53 UTC, jayhan1109 requested changes

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/components/slideshow/MainList.js
> +              <img src={heartImg} alt=''></img>
<img src={heartImg} alt=''/>

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/components/slideshow/MainList.js
> +      url: item.recipeImage ? item.recipeImage : tempFood,
item.recipeImage ?? tempFood

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/components/slideshow/MainList.js
> +              <img src={heartImg} alt=''></img>
image.user.name ?? 'No name'
이거 안되면 아마도
image.user?.name ?? 'No name'

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/pages/LandingPage.js
> +        setbrunch(res.data.brunch)
prettier

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/pages/LandingPage.js
>        const res = await axios.get('/api/recipes/landing')
const {brunch, best, snack} = res.data
하면 좀 더 깔끔 할 듯

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/pages/SearchPage.js
> +  const [Loading, setLoading] = useState(false);
loading

2022-12-21 22:53 UTC, jayhan1109 commented on client/src/pages/SearchPage.js
> +        {Loading === true ? <img src={gif} /> : <div className='search-container'>
prettier

2022-12-22 02:12 UTC, YunDobi commented
> 추가한

버튼위치는 계속 바꿔보고잇는중이긴 한데 처음에 랜딩되기 전에가 문제라 차차고쳐가는중

2022-12-24 07:18 UTC, jayhan1109 commented
> 버튼위치는 계속 바꿔보고잇는중이긴 한데 처음에 랜딩되기 전에가 문제라 차차고쳐가는중 그리고 로딩 스크린이 어떤거야?

https://github.com/cook-king-van/cook-king/blob/Develop/client/src/components/Spinner.js
이거

2022-12-24 07:39 UTC, YunDobi commented
그걸로 바꾸고 푸쉬햇어

2022-12-24 08:04 UTC, jayhan1109 approved these changes
LGTM

그 플러스 버튼 에러는 티켓 새로 만들어서 해도 돼

2022-12-24 08:56 UTC, merged